### ISSUE TITLE
自动公告

### ISSUE THREAD

**Issue by SakuraKoi** [SakuraKoi/BattlefieldChat#16]
- [ ] 列表发送
- [ ] 发送间隔
- [ ] 配置保存
- [ ] 从txt中加载消息列表 (一行一条)
- [ ] 模拟按键模式
- [ ] 游玩状态下暂停模拟按键避免干扰游戏
> https://stackoverflow.com/questions/8820615/how-to-check-in-c-if-the-system-is-active
- [ ] 注入bf1.exe直接call ChatManager.sendMessage() ( 与DLL使用IPC通信 )

**Comment by SoraKasvgano** [comment]
艹 新版本太臭了

**Comment by SakuraKoi** [comment]
#12
