### ISSUE TITLE
找不到QQ.exe 不知道什么原因

### ISSUE THREAD

**Issue by yakumoice** [SakuraKoi/BattlefieldChat#19]
![image](https://github.com/SakuraKoi/BattlefieldChat/assets/83846912/a0f52caa-9ca1-4814-91e0-d8dc828340bd)

**Comment by SakuraKoi** [comment]
程序和QQ一点关系都没有, 这个弹窗也不应该是BattlefieldChat发出的
自行检查你的电脑环境中是否有什么乱七八糟的东西注进了BattlefieldChat进程里面
