### ISSUE TITLE
增加根据聊天框自动切换系统输入法功能

### ISSUE THREAD

**Issue by CrazyZhang666** [SakuraKoi/BattlefieldChat#20]
目前按J打开聊天了，并不会切换输入法，需要玩家手动切换。玩家输入玩中文后，回到游戏要再次手动切换到美式键盘，这样每次输入都要重复上面操作，比较麻烦

希望可以：
打开聊天框自动切换输入法到中文状态，输入完成按回车回到游戏输入法切到美式键盘，依次循环

![image](https://github.com/SakuraKoi/BattlefieldChat/assets/28080853/18fb94f6-e9b9-4451-8d6f-1340e7eb7f70)

**Comment by CrazyZhang666** [comment]
这是C#处理方式
![image](https://github.com/SakuraKoi/BattlefieldChat/assets/28080853/326bb7c4-6012-4162-8d97-8d5a2d2d0293)
![image](https://github.com/SakuraKoi/BattlefieldChat/assets/28080853/370c1896-9ba8-4a62-97be-128b5469e7a6)

**Comment by SakuraKoi** [comment]
> 回到游戏要再次手动切换到美式键盘

为什么要切换到美式键盘, 直接开着输入法继续游戏就行
bf1禁用了输入法, 因此开着输入法并不影响游戏操作

> 打开聊天了，并不会切换输入法

如果你不切换到美式键盘, 就没有切换输入法的必要, 因为打开聊天框直接就是中文输入法
