### ISSUE TITLE
输入界面的快速模式切换按钮

### ISSUE THREAD

**Issue by SakuraKoi** [SakuraKoi/BattlefieldChat#3]
这个就绪旁边我觉得可以加个中文和拼音和切换按钮，比如 中/拼，这样不用每次到外面切换了

_Originally posted by @CrazyZhang666 in https://github.com/SakuraKoi/BattlefieldChat/issues/2#issuecomment-788557397_

**Comment by Firsgith** [comment]
> 这个就绪旁边我觉得可以加个中文和拼音和切换按钮，比如 中/拼，这样不用每次到外面切换了
> 
> _Originally posted by @CrazyZhang666 in [#2 (comment)](https://github.com/SakuraKoi/BattlefieldChat/issues/2#issuecomment-788557397)_

想法真的很牛。我觉得这个功能非常方便。刚刚试了，频繁切换软件，会导致软件闪退。
